In [2]:
# zip - zip() pairs elements from two or more lists (or tuples) index-wise.
l1 = [1,2,3]
l2 = [4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [2]:
# Using list
import time
size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
result = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(end - start)

0.22449398040771484


In [6]:
# Using numpy array
import numpy as np
import time
size = 1_000_000
arr1 = np.array(list(range(size)))
arr2 = np.array(list(range(size)))
start = time.time()
result = arr1 + arr2
end = time.time()
print(end - start)

0.0026712417602539062


In [8]:
# Creating 1D array
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [14]:
# Creating 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print(type(arr2))
arr2.shape

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


(2, 3)

In [22]:
# Memory efficiency
'''the sys module in Python is used to interact with the Python interpreter itself.
Think of it like a bridge between your Python code and the system/environment where Python is running.'''

import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print(f"Python list size : {sys.getsizeof(list_data) * len(list_data)} bytes")
print("Numpy array size: ", numpy_data.nbytes, "bytes")

Python list size : 8056000 bytes
Numpy array size:  8000 bytes
