In [2]:
import numpy as np

**1. Creating an array from the list**

In [59]:
one_dim_array = np.array([1,2,3])
print(one_dim_array)

two_dim_array = np.array([[1,2,3], [4,5,6]])
print("\n", two_dim_array)

[1 2 3]

 [[1 2 3]
 [4 5 6]]


**2. Creating an array from Scratch**

In [7]:
np.zeros((3,3))  # 3x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))  # 3x3 array of ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((3,3), 7)  # 3x3 array filled with 7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [3]:
np.eye(4)   # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.arange(1,12, 2)  #It works like ranges

array([ 1,  3,  5,  7,  9, 11])

In [32]:
np.linspace(1,100,4)   #Evenly spaced

array([  1.,  34.,  67., 100.])

**3. Checking Array Properties**

In [41]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr)
print("\nShape: ", arr.shape)   # Gives the shape of an array which is 4x3
print("Size: ", arr.size)       # Give total number of elements present in an array
print("Dimensions: ", arr.ndim) # Returns the dimension of the array
print("Data Type: ", arr.dtype) # int64 (or int32 depending on Windows Architecture)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape:  (4, 3)
Size:  12
Dimensions:  2
Data Type:  int64


**4. Changing Data Types**

In [46]:
arr = np.array([1,2,3], dtype=np.float32)  # Explicit Type
print(arr)
print(arr.dtype)

arr_int = arr.astype(np.int32)
print(arr_int)

[1. 2. 3.]
float32
[1 2 3]


**5. Reshaping and Flattening Arrays**

In [58]:
my_arr =  np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])                       
print(my_arr)       # The array is of shape 4x3
reshaped = my_arr.reshape((2,6))
print("\n", reshaped)  # Array reshaped into 2x6

flattened = my_arr.flatten()
print("\n", flattened)   #Converting 2D array in 1D

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 [ 1  2  3  4  5  6  7  8  9 10 11 12]
