In [1]:
import numpy as np

**1. Understanding Axes in Numpy: Each dimension in a NumPy array is called an axis. Axes are numbered starting
from 0.
For example:
1D array → 1 axis (axis 0), 
2D array → 2 axes (axis 0 = rows, axis 1 = columns), 
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)**

In [3]:
arr = arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**1. Axis 0 (rows)** → Operations move down the columns.
**2. Axis 1 (columns)** → Operations move across the rows

In [17]:
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [26]:
print(np.sum(arr, axis=0))
print("\n", np.sum(arr, axis=1))

[12 15 18]

 [ 6 15 24]


**2. Indexing in MultiDimensional Arrays.**

In [21]:
print(arr[0][1])   # Row index -> 0, Column index -> 1
print(arr[1][2])   # Row index -> 1, Column index -> 2
# Python Provides a feature to access the element in Multidimensional arrays
print(arr[2, 2])  # Row index -> 2, Column index -> 2

2
6
9


**3. Slicing in Multidimensional arrays**

In [28]:
print(arr[0:2, 1:])  # Extract first two rows and extract last two columns
print("\n", arr[0:, 1:])   # Extract all rows and extract last two columns

[[2 3]
 [5 6]]

 [[2 3]
 [5 6]
 [8 9]]


**4. Indexing in 3d array** : For 3D arrays, the first index refers to the “depth” (sheets of data).


In [32]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])
print(arr3D)
# Output of arr3D.shape is → (depth, rows, columns)
print("\n", arr3D.shape)     #(2,      2,       3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 (2, 2, 3)


**Accessing elements in 3D array**

In [48]:
print(arr3D[1, 1, 2])    # depth-1, row-1, column 2
print("\n", arr3D[0, 1, 2])    # depth-0, row-1, column 2
print("\n", arr3D[:, 1, 1])    # depth-both 2D arrays, row-1, column 1
print("\n", arr3D[:, 0, :])    # depth-both 2D arrays, row-0, column all

12

 6

 [ 5 11]

 [[1 2 3]
 [7 8 9]]


**5. Changing Data Along Axis.**

In [59]:
arr3D[:, 0, :] = 0
arr3D[:, 1, :] = 1
print(arr3D)

[[[0 0 0]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]]]
