In [2]:
import numpy as np
import time

**Broadcasting**- Now, we’ll explore how to make your code faster with vectorization and
broadcasting in NumPy. These techniques are key to boosting performance in
numerical operations by avoiding slow loops and memory inefficiency.

**1. Looping over arrays in python**

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500])
result = []
start = time.time()
for num in arr:
    result.append(num**2)
end= time.time()
print(result)
print(end - start)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25), np.int64(36), np.int64(49), np.int64(64), np.int64(81), np.int64(100), np.int64(121), np.int64(144), np.int64(169), np.int64(196), np.int64(225), np.int64(256), np.int64(289), np.int64(324), np.int64(361), np.int64(400), np.int64(441), np.int64(484), np.int64(529), np.int64(576), np.int64(625), np.int64(676), np.int64(729), np.int64(784), np.int64(841), np.int64(900), np.int64(961), np.int64(1024), np.int64(1089), np.int64(1156), np.int64(1225), np.int64(1296), np.int64(1369), np.int64(1444), np.int64(1521), np.int64(1600), np.int64(1681), np.int64(1764), np.int64(1849), np.int64(1936), np.int64(2025), np.int64(2116), np.int64(2209), np.int64(2304), np.int64(2401), np.int64(2500), np.int64(2601), np.int64(2704), np.int64(2809), np.int64(2916), np.int64(3025), np.int64(3136), np.int64(3249), np.int64(3364), np.int64(3481), np.int64(3600), np.int64(3721), np.int64(3844), np.int64(3969), np.int64(4096), np.int64(4225), np

**2. Vectorization (Fixing the Loop Problem)**

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500])
start = time.time()
result = arr ** 2
end= time.time()
print(result)
print(end - start)

[     1      4      9     16     25     36     49     64     81    100
    121    144    169    196    225    256    289    324    361    400
    441    484    529    576    625    676    729    784    841    900
    961   1024   1089   1156   1225   1296   1369   1444   1521   1600
   1681   1764   1849   1936   2025   2116   2209   2304   2401   2500
   2601   2704   2809   2916   3025   3136   3249   3364   3481   3600
   3721   3844   3969   4096   4225   4356   4489   4624   4761   4900
   5041   5184   5329   5476   5625   5776   5929   6084   6241   6400
   6561   6724   6889   7056   7225   7396   7569   7744   7921   8100
   8281   8464   8649   8836   9025   9216   9409   9604   9801  10000
  10201  10404  10609  10816  11025  11236  11449  11664  11881  12100
  12321  12544  12769  12996  13225  13456  13689  13924  14161  14400
  14641  14884  15129  15376  15625  15876  16129  16384  16641  16900
  17161  17424  17689  17956  18225  18496  18769  19044  19321  19600
  1988

**3. Broadcasting: Scaling Arrays Without Extra Memory**

In [13]:
arr2 = np.array([10,20,30,40,50])
result = arr2 + 10  #Broadcasting : 10 added to all elements
print(result)

[20 30 40 50 60]


**4. Broadcasting of Array with Different Shapes**

In [16]:
# Broadcasting with Two Arrays
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])
sum = arr1 + arr2
print(sum)

[11 22 33]


In [18]:
# Broadcasting a 2D Array and a 1D Array
arr1 = np.array([[10,20,30], [40,50,60]])
arr2 = np.array([1,2,3])
sum = arr1 + arr2
print(sum)

[[11 22 33]
 [41 52 63]]


**5. Hands-on: Applying Broadcasting to Real-World Scenarios**

In [19]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using the broadcast
normalize_data = (data-mean)/std
print(normalize_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
